# Generated by Django 3.1.8 on 2021-04-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210426_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='case',
        ),
        migrations.AddField(
            model_name='event',
            name='case',
            field=models.ManyToManyField(to='users.Case'),
        ),
        migrations.AlterField(
            model_name='event',
            name='x_coor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='y_coor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
