# Generated by Django 3.1.8 on 2021-04-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210428_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_no',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
